name: trading-bot-v3

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Navigate to the correct directory
        run: cd /home/runner/work/trading-bot-v3/trading-bot-v3

      - name: List directory contents
        run: ls -al

      - name: Install npm dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t rokondoc/trading-bot-v3 -f Dockerfile .

      - name: Publish image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push rokondoc/trading-bot-v3:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from Docker Hub
        run: docker pull rokondoc/trading-bot-v3:latest

      - name: Stop and remove existing container (if any)
        run: |
          docker stop reactContainer || true
          docker rm reactContainer || true

      - name: Run Docker container
        run: docker run -d -p 3000:80 --name reactContainer rokondoc/trading-bot-v3

