name: trading-bot-v3
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        run: docker build -t rokondoc/trading-bot-v3 .
      - name: Publish image to docker hub
        run: docker push rokondoc/trading-bot-v3:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull rokondoc/trading-bot-v3:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer || true 
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer rokondoc/trading-bot-v3
